server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    redis:
      url: ${REDIS_URL}
    jpa:
      repositories:
        bootstrap-mode: default

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}