version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: data_ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: data_ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.0
    container_name: data_ecommerce-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: